In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('laporan_kuisioner_10_8_2026_1786337462663.xlsx', sheet_name='6. upload dash(cleaned)')
df.head()

,Id Kec Desa,Kode Kecamatan,Kecamatan,Kode Desa,Desa,Id Komoditas,Komoditas,Id Kualitas,Kualitas,Satuan,Harga,Tanggal Pendataan,Minggu,No Bulan,Bulan,Periode,No Periode,Asal Barang,Periode (Tahun-Bulan-Minggu),Tahun
0,40002.0,40.0,SEKAYU,2.0,SUNGAI MEDAK,1,Beras,NaN,NaN,kg,0,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1,41011.0,41.0,LAIS,11.0,LAIS,1,Beras,1.0,Selancar,kg,15000,2026-05-12,3.0,5.0,Mei,Mei-3,05-3,Warung,2026-05-3,2026.0
2,101015.0,101.0,LALAN,15.0,KARANG MUKTI,1,Beras,18.0,Lainnya,kg,12000,2026-07-16,3.0,7.0,Juli,Jul-3,07-3,Pabrik padi,2026-07-3,2026.0
3,92010.0,92.0,BABAT SUPAT,10.0,SUMBER JAYA,1,Beras,1.0,Selancar,kg,15000,2026-07-01,1.0,7.0,Juli,Jul-1,07-1,BETUNG,2026-07-1,2026.0
4,92009.0,92.0,BABAT SUPAT,9.0,BANDAR TENGGULANG,1,Beras,3.0,Topi Koki,kg,15000,2026-05-04,2.0,5.0,Mei,Mei-2,05-2,Pasar sungai lilin,2026-05-2,2026.0

In [6]:
missing_values = df.isnull().sum()
missing_values

Id Kec Desa                      620
Kode Kecamatan                   300
Kecamatan                        300
Kode Desa                        620
Desa                             620
Id Komoditas                       0
Komoditas                          0
Id Kualitas                      312
Kualitas                         312
Satuan                             0
Harga                              0
Tanggal Pendataan               1047
Minggu                          1047
No Bulan                        1047
Bulan                           1047
Periode                         1047
No Periode                      1047
Asal Barang                        0
Periode (Tahun-Bulan-Minggu)    1047
Tahun                           1047
dtype: int64

In [7]:
duplicate_values = df.duplicated().sum()
duplicate_values

np.int64(855)

In [8]:
df["Harga"] = pd.to_numeric(df["Harga"], errors="coerce")

In [9]:
df["Harga"].describe()

count      4040.000000
mean      31873.138614
std       35685.001638
min           0.000000
25%        4000.000000
50%       21000.000000
75%       45000.000000
max      300000.000000
Name: Harga, dtype: float64

In [10]:
df["Harga"] = df["Harga"].apply(
    lambda x: x * 1000 if 0 < x < 100 else x
)

In [11]:
df.head()

,Id Kec Desa,Kode Kecamatan,Kecamatan,Kode Desa,Desa,Id Komoditas,Komoditas,Id Kualitas,Kualitas,Satuan,Harga,Tanggal Pendataan,Minggu,No Bulan,Bulan,Periode,No Periode,Asal Barang,Periode (Tahun-Bulan-Minggu),Tahun
0,40002.0,40.0,SEKAYU,2.0,SUNGAI MEDAK,1,Beras,NaN,NaN,kg,0,NaT,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1,41011.0,41.0,LAIS,11.0,LAIS,1,Beras,1.0,Selancar,kg,15000,2026-05-12,3.0,5.0,Mei,Mei-3,05-3,Warung,2026-05-3,2026.0
2,101015.0,101.0,LALAN,15.0,KARANG MUKTI,1,Beras,18.0,Lainnya,kg,12000,2026-07-16,3.0,7.0,Juli,Jul-3,07-3,Pabrik padi,2026-07-3,2026.0
3,92010.0,92.0,BABAT SUPAT,10.0,SUMBER JAYA,1,Beras,1.0,Selancar,kg,15000,2026-07-01,1.0,7.0,Juli,Jul-1,07-1,BETUNG,2026-07-1,2026.0
4,92009.0,92.0,BABAT SUPAT,9.0,BANDAR TENGGULANG,1,Beras,3.0,Topi Koki,kg,15000,2026-05-04,2.0,5.0,Mei,Mei-2,05-2,Pasar sungai lilin,2026-05-2,2026.0

In [14]:
df.isna().sum()

Id Kec Desa                      620
Kode Kecamatan                   300
Kecamatan                        300
Kode Desa                        620
Desa                             620
Id Komoditas                       0
Komoditas                          0
Id Kualitas                      312
Kualitas                         312
Satuan                             0
Harga                              0
Tanggal Pendataan               1047
Minggu                          1047
No Bulan                        1047
Bulan                           1047
Periode                         1047
No Periode                      1047
Asal Barang                        0
Periode (Tahun-Bulan-Minggu)    1047
Tahun                           1047
dtype: int64

In [19]:
df = df.dropna()

In [20]:
df.isna().sum()

Id Kec Desa                     0
Kode Kecamatan                  0
Kecamatan                       0
Kode Desa                       0
Desa                            0
Id Komoditas                    0
Komoditas                       0
Id Kualitas                     0
Kualitas                        0
Satuan                          0
Harga                           0
Tanggal Pendataan               0
Minggu                          0
No Bulan                        0
Bulan                           0
Periode                         0
No Periode                      0
Asal Barang                     0
Periode (Tahun-Bulan-Minggu)    0
Tahun                           0
dtype: int64

In [21]:
df

,Id Kec Desa,Kode Kecamatan,Kecamatan,Kode Desa,Desa,Id Komoditas,Komoditas,Id Kualitas,Kualitas,Satuan,Harga,Tanggal Pendataan,Minggu,No Bulan,Bulan,Periode,No Periode,Asal Barang,Periode (Tahun-Bulan-Minggu),Tahun
1,41011.0,41.0,LAIS,11.0,LAIS,1,Beras,1.0,Selancar,kg,15000,2026-05-12,3.0,5.0,Mei,Mei-3,05-3,Warung,2026-05-3,2026.0
2,101015.0,101.0,LALAN,15.0,KARANG MUKTI,1,Beras,18.0,Lainnya,kg,12000,2026-07-16,3.0,7.0,Juli,Jul-3,07-3,Pabrik padi,2026-07-3,2026.0
3,92010.0,92.0,BABAT SUPAT,10.0,SUMBER JAYA,1,Beras,1.0,Selancar,kg,15000,2026-07-01,1.0,7.0,Juli,Jul-1,07-1,BETUNG,2026-07-1,2026.0
4,92009.0,92.0,BABAT SUPAT,9.0,BANDAR TENGGULANG,1,Beras,3.0,Topi Koki,kg,15000,2026-05-04,2.0,5.0,Mei,Mei-2,05-2,Pasar sungai lilin,2026-05-2,2026.0
5,101024.0,101.0,LALAN,24.0,AGUNG JAYA,1,Beras,3.0,Topi Koki,kg,16500,2026-06-22,4.0,6.0,Juni,Jun-4,06-4,PALEMBANG,2026-06-4,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4034,100028.0,100.0,BAYUNG LENCIR,28.0,MANGSANG,20,Jeruk,44.0,Sedang Segar,kg,35000,2026-06-04,1.0,6.0,Juni,Jun-1,06-1,bayung lencir,2026-06-1,2026.0
4035,91009.0,91.0,KELUANG,9.0,TANJUNG DALAM,20,Jeruk,44.0,Sedang Segar,kg,25000,2026-07-06,2.0,7.0,Juli,Jul-2,07-2,Sungai lilin,2026-07-2,2026.0
4036,100028.0,100.0,BAYUNG LENCIR,28.0,MANGSANG,20,Jeruk,44.0,Sedang Segar,kg,28000,2026-07-16,3.0,7.0,Juli,Jul-3,07-3,bayung lencir,2026-07-3,2026.0
4037,22009.0,22.0,PLAKAT TINGGI,9.0,AIR PUTIH ULU,20,Jeruk,44.0,Sedang Segar,kg,23000,2026-06-26,4.0,6.0,Juni,Jun-4,06-4,Sekayu,2026-06-4,2026.0
4039,92009.0,92.0,BABAT SUPAT,9.0,BANDAR TENGGULANG,20,Jeruk,44.0,Sedang Segar,kg,25000,2026-04-24,4.0,4.0,April,Apr-4,04-4,Pasar sungai lilin,2026-04-4,2026.0

In [22]:
df.to_excel("data-preprocessing.xlsx", index=False)